[package]
name = "conceal-core"
version = "0.1.0"
authors = ["Tyr Chen <tyr.chen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
snow = "0.6"
thiserror = "1"
tokio = { version = "0.2", features = ["fs", "io-util"] }
tracing = "0.1"

[dev-dependencies]
anyhow = "1"
criterion = "0.3"
rand = "0.7"
tempfile = "3"
tokio = { version = "0.2", features = ["macros"]}


[[bench]]
name = "bench_conceal"
harness = false

